name: Build Docker Container

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ] # Запускати при створенні тегів, напр. v1.0
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (Опціонально)
        # Якщо ви хочете публікувати в Docker Hub,
        # додайте DOCKERHUB_USERNAME і DOCKERHUB_TOKEN в Секрети репозиторію
        # uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push спрацює тільки при створенні тегу
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
          # Замініть 'your-docker-user' на ваш логін в Docker Hub
          tags: your-docker-user/myuniq:latest, your-docker-user/myuniq:${{ github.ref_name }}